package br.com.bms.webservice.domain.model.funcionario.enuns;

public enum AreaFormacaoEnum {

	ADMINISTRATIVA("Administrativa"),
	ADMINISTRATIVO_COMERCIAL("Administrativo Comercial"),
	ADMINISTRATIVO_OPERACIONAL("Administrativo/ Operacional"),
	AGRONOMIA("Agronômica/ Engenharia Agrnômica/ Agribusiness"),
	AGROPECUARIA("Agropecuária/ Veterinária/ Agrobusiness"),
	ENSINO_MEDIO("APENAS ENSINO MÉDIO"),
	ARQUITETURA("Arquitetura/ Decoração/ Urbanismo"),
	ARTES("Artes"),
	ARTES_GRAFICAS("Artes Gráficas"),
	ATENDIMENTO_CLIENTE("Atendimento ao Cliente/ Call Center/ Telemarketing"),
	AUTOMACAO("Automação Industrial/ Comercial"),
	AVIACAO("Aviação/ Aeronáutica"),
	BANCARIA("Banária/ Private Corporate Bank"),
	BIBLIOTECONOMIA("Biblioteconomia"),
	BIOLOGIA("Biologia"),
	BIOTECNOLOGIA("Biotecnologia/ Biomédicas/ Bioquímica"),
	COMERCIAL("Cormercial/ Vendas"),
	COMERCIO("Comércio Exterior/ Trade/ Importsção/ Exportação"),
	COMPRAS("Compras"),
	CONSTRUCAO_CIVIL("Construção Civil/ Engenharia Civil"),
	CONTABILIDADE("Contabilidade"),
	DEPARTAMENTO_PESSOAL("Departamento Pessoal"),
	DESENHO("Desenho Industrial"),
	ECONOMIA("Econonia"),
	EDUCACAO_ENSINO_IDIOMAS("Educação/ Ensino/ Idiomas"),
	ENFERMAGEM("Enfermagem"),
	ENGENHARIA_ALIMENTOS("Engenharia de Alimentos"),
	ENGENHARIA_MATERIAIS("Engenharia de Materiais"),
	ENGENHARIA_MINAS("Engenharia de Minas"),
	ENGENHARIA_PRODUCAO("Engenharia de Produção/ Industrial"),
	ENGENHARIA_ELETRICA("Engenharia Elétrica/ Eletrônica"),
	ENGENHARIA_MECANICA("Engenharia Mecânica/ Mecatrônica"),
	ESPORTES("Esportes/ Educação Física"),
	ESTATISTICA("Estatística/ Matemática/ Atuária"),
	ESTETICA("Estética Corporal"),
	FARMACIA("Farmácia"),
	FINANCEIRA("Financeira/ Administrativa"),
	FISIOTERAPIA("Fisioterapia"),
	FONOAUDIOLOGIA("Fonoaudiologia"),
	GEOLOGIA("Geografia/ Engenharia Agrimensura"),
	HOTELARIA("Hotelaria/ Turismo"),
	INDUSTRIAL("Industrial"),
	INFORMATICA("Informática/ TI/ Engenharia da Computação"),
	INTERNET("Internet/ E-Commerce/ E-Business/ Web/ Web Designer"),
	JORNALISMO("Jornalismo"),
	JURIDICA("Jurídica"),
	LOGISTICA("Logística/ Suprimentos"),
	MANUTENCAO("Manutenção"),
	MARKETING("Marketing"),
	MEDICO("Médico/ Hospitalar"),
	MEIO_AMBIENTE("Meio Ambiente/ Ecologia/ Engenharia de Meio Ambiente"),
	MODA("Moda"),
	NUTRICAO("Nutrição"),
	ODONTOLOGIA("Odontologia"),
	PSICOLOGIA("Psicologia Clínica/ Hospitalar"),
	PUBLICIDADE("Publicidade e Propaganda"),
	QUALIDADE("Qualidade"),
	QUIMICA("Química/ Engenharia Química"),
	RECURSOS_HUMANOS("Recursos Humanos"),
	RELACOES_INTERNACIONAIS("Relações Internacionais"),
	RELACOES_PUBLICAS("Relações Públicas"),
	RESTAURANTE("Restaurante"),
	SECRETARIADO("Secretariado"),
	SEGURANCA_TRABALHO("Segurança do Trabalho"),
	SEGURANCA_PATRIMONIAL("Segurança Patrimonial"),
	SEGUROS("Seguros"),
	SERVICO_SOCIAL("Serviço Social"),
	TECNICA("Técnica"),
	TECNICO_COMERCIAL("Técnico-Comencial"),
	TELECOMUNICACOES("Telecomunicações/ Engenharia de Telecomunicações"),
	TERAPIA("Terapia Ocupacional"),
	TEXTIL("Têxtil/ Engenharia Têxtil"),
	TRADUTOR("Tradutor/ Intérprete"),
	TRANSPORTES("Transportes"),
	ZOOTECNIA("Zootecnia");
	
	private String areaFormacao;

	private AreaFormacaoEnum(String areaFormacao) {
		this.areaFormacao = areaFormacao;
	}

	public String getAreaFormacao() {
		return areaFormacao;
	}
}
